### ISSUE TITLE
TypeError: namedTags.includes is not a function

### ISSUE THREAD

**Issue by ichiriac** [togajs/tunic#1]
Hi @shannonmoeller 

I have the following error message :

```cli
     TypeError: namedTags.includes is not a function
      at parseTag (node_modules/tunic/dist/tunic.js:198:39)
      at node_modules/tunic/dist/tunic.js:158:11
      at Array.map (native)
      at parseComment (node_modules/tunic/dist/tunic.js:157:14)
      at parseBlocks (node_modules/tunic/dist/tunic.js:121:21)
      at Object.parse (node_modules/tunic/dist/tunic.js:99:11)`
```

To reproduce the bug :

```js
var tunic = require('tunic'); // @version 2.0.0
tunic.parse('/**\n             * @var bar\n             */');
```

Am I missing something ?

**Comment by ichiriac** [comment]
found why here : https://github.com/nodejs/node/issues/5715

my nodejs version is V8 `4.2`

You could use indexOf instead to make the code more compatible, or run node with `--harmony_array_includes` flag

**Comment by shannonmoeller** [comment]
You are correct. That has been changed to indexOf in newer code, but that code isn't ready for a release. I'll see about fixing that. Thanks!

**Comment by ichiriac** [comment]
thanks @shannonmoeller, meanwhile I will fork and make a fix commit in order to use it with npm
